### ISSUE TITLE
Supply release notes

### ISSUE THREAD

**Issue by oddgames-david** [jenkinsci/plasticscm-plugin#22]
Are you able to supply release notes?

Codice always has excellent release notes and it's hard to know if I should take the time to update my environment.

**Comment by mig42** [comment]
We update the Changelog every release in the Jenkins Wiki page: https://wiki.jenkins.io/display/JENKINS/PlasticSCM+plugin#PlasticSCMPlugin-Changelog . Do you mean right here in the GitHub repo?

**Comment by oddgames-david** [comment]
I meant on github but now I know where they are I'm good.

**Comment by mig42** [comment]
Cool, we'll add the changelog to the repo at some point.
