### ISSUE TITLE
Expose the feature used in the message column to allow other metadata/links

### ISSUE THREAD

**Issue by oddgames-david** [jenkinsci/plasticscm-plugin#23]
Are you able to process currentBuild.description and create the same style of links/bubble text for our own meta data?

I'd love to be able to go from this:

![image](https://user-images.githubusercontent.com/1932174/64084446-2998a400-cd5e-11e9-9a72-c2461433ef35.png)

to something like this (ignore the design skills):

![image](https://user-images.githubusercontent.com/1932174/64084546-19cd8f80-cd5f-11e9-9479-aa14b1500b84.png)

**Comment by oddgames-david** [comment]
Delete if not applicable, I think i'm mistaken, it's a blueocean feature.

**Comment by mig42** [comment]
Yes, unfortunately our plugin doesn't implement all the BlueOcean features at the moment. We are aware of that and we'd really like to change it, but I'm afraid we can't commit to a release date for it at the moment.
