### ISSUE TITLE
Wrong path delimiters on MacOS

### ISSUE THREAD

**Issue by Mars709** [jenkinsci/plasticscm-plugin#39]
Executing cm command on MacOS causing this problem:
![изображение](https://user-images.githubusercontent.com/74378299/98987441-38204500-2537-11eb-91f7-ff9fe6a63e70.png)

cm unco --all --silent <path> will not run with backslash delimiters.

Workaround is to run "cm unco" manually through "sh script:" but it's a kludge)

**Comment by mig42** [comment]
Hi @Mars709 ,

Is this happening for you in the latest version (4.0)? If so, could you tell us about your setup? We're guessing that you have a Windows controller and a macOS agent, but we'd like to confirm.

Thanks!
