### ISSUE TITLE
"No such file or directory" on MacOS node

### ISSUE THREAD

**Issue by mmttim** [jenkinsci/plasticscm-plugin#41]
I'm trying to call the Plastic plugin on a MacOS node. The master node is a Linux system running in a Docker container.

Checking out files from our Plastic repo didn't work from the beginning, I figured out that I need to add "/usr/local/bin" to the Path environment variable because Jenkins somehow is not using the correct ones on the node. So far so good, because when I call "cm" from shell script before calling the plugin I get the default essential commands message from the cm tool.

The problem: The plugin still can't find "cm" and is throwing the error "error=2, No such file or directory". Does anyone know why this happens?

I also echo the path variable at the beginning of the job. This is the content: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

The launch method of the node is "Launch aget by connecting it to the master"

**Comment by mig42** [comment]
Hi @mmttim , could you provide more details about the issue? Log and output would be very useful to us.

**Comment by mmttim** [comment]
We not really have a log, just the data we mentioned in the first post.

To be honest we stopped trying at some point. We will try this again with multiple Windows nodes in the future.

**Comment by mig42** [comment]
Hi @mmttim,

Version 4.0 of our plugin exposes `cm` as a Jenkins Tool, including a system to automatically downloading and installing it if it can't be found in the current machine (controller or agent).
